=== faktorips/faktorips.base/faktorips-schemas/src/main/resources/EnumContent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.faktorzehn.org" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.faktorzehn.org">

    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation='https://www.w3.org/2009/01/xml.xsd' />
    <xsd:include id="ips" schemaLocation='ips-global.xsd' />

    <xsd:element name="EnumContent">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="1">
                <xsd:element ref="ExtensionProperties" minOccurs="0" maxOccurs="1" />
                <xsd:element name="Description" type="Description" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="EnumValue" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element name="EnumAttributeReference" type="EnumAttributeReference" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="enumType" type="qualifiedName" use="required" />
            <xsd:attribute ref="xml:space" />
        </xsd:complexType>
        <xsd:unique name="UniqueIdInPolicyCmptType">
            <xsd:selector xpath="*" />
            <xsd:field xpath="@id" />
        </xsd:unique>
    </xsd:element>

    <xsd:element name="EnumValue">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="1">
                <xsd:element ref="ExtensionProperties" minOccurs="0" maxOccurs="1" />
                <xsd:element name="Description" type="Description" minOccurs="1" maxOccurs="unbounded" />
                <xsd:element name="EnumAttributeValue" type="EnumAttributeValue" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="UniqueIdInEnumValue">
            <xsd:selector xpath="*" />
            <xsd:field xpath="@id" />
        </xsd:unique>
    </xsd:element>

    <xsd:complexType name="EnumAttributeReference">
        <xsd:attributeGroup ref="name" />
    </xsd:complexType>


    <xsd:complexType name="EnumAttributeValue" mixed="true">
        <xsd:sequence minOccurs="1" maxOccurs="1">
            <xsd:element ref="ExtensionProperties" minOccurs="0" maxOccurs="1" />
            <xsd:element ref="InternationalString" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="isNull" type="boolean" use="required" />
    </xsd:complexType>
</xsd:schema>

=== faktorips/faktorips.base/runtime/faktorips-runtime/src/test/resources/org/faktorips/runtime/testrepository/testenum/produkt/ExtensibleEnum.xml
<?xml version="1.0" encoding="UTF-8"?>
<EnumContent xmlns="http://www.faktorzehn.org" enumType="produkt.ExtensibleEnum" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.faktorzehn.org https://doc.faktorzehn.org/schema/faktor-ips/23.6/EnumContent.xsd" xml:space="preserve">
 <Description locale="en">The Description</Description>
 <Description locale="de">Die Beschreibung</Description>
 <EnumValue>
  <Description locale="en"/>
  <Description locale="de"/>
  <EnumAttributeValue isNull="false">1</EnumAttributeValue>
  <EnumAttributeValue isNull="false">extensible_enum_1</EnumAttributeValue>
 </EnumValue>
 <EnumValue>
  <Description locale="en"/>
  <Description locale="de"/>
  <EnumAttributeValue isNull="false">2</EnumAttributeValue>
  <EnumAttributeValue isNull="false">extensible_enum_2</EnumAttributeValue>
 </EnumValue>
 <EnumAttributeReference name="id"/>
 <EnumAttributeReference name="name"/>
</EnumContent>
