=== faktorips/faktorips.base/faktorips-schemas/src/main/resources/TableContents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.faktorzehn.org" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.faktorzehn.org" xmlns:ts="http://www.faktorzehn.org">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation='http://www.w3.org/2009/01/xml.xsd' />
    <xsd:include id="ips" schemaLocation='ips-global.xsd' />

    <xsd:element name="TableContents">
        <xsd:complexType>
            <xsd:sequence minOccurs="1" maxOccurs="1">
                <xsd:element ref="ExtensionProperties" minOccurs="0" maxOccurs="1" />
                <xsd:element name="Description" type="Description" minOccurs="1" maxOccurs="unbounded" />
                <xsd:element ref="ColumnTableReference" minOccurs="0" maxOccurs="unbounded" />
                <xsd:element ref="Rows" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="numOfColumns" use="required" type="int" />
            <xsd:attribute name="tableStructure" type="string" use="required"/>
            <xsd:attribute ref="xml:space" />
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="ColumnTableReference">
        <xsd:complexType>
            <xsd:attribute name="name" type="string" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Rows">
        <xsd:complexType mixed="true">
            <xsd:sequence>
                <xsd:element ref="ExtensionProperties" minOccurs="0" maxOccurs="1" />
                <xsd:element ref="Row" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
            <xsd:attribute name="format" use="required">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="XML" />
                        <xsd:enumeration value="CSV" />
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:attribute>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="Row">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="ExtensionProperties" minOccurs="0" maxOccurs="1" />
                <xsd:element type="xsd:string" name="Value" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== faktorips/faktorips.base/runtime/faktorips-runtime/src/test/resources/org/faktorips/runtime/internal/TableTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<TableContents xmlns="http://www.faktorzehn.org" numOfColumns="3" tableStructure="tables.TestTable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.faktorzehn.org https://doc.faktorzehn.org/schema/faktor-ips/23.6/TableContents.xsd" xml:space="preserve">
    <Description locale="en">TestDescription</Description>
    <Description locale="fr"/>
    <Description locale="de">TestBeschreibung</Description>
    <ColumnTableReference name="company"/>
    <ColumnTableReference name="Gender"/>
    <ColumnTableReference name="rate"/>
    <Rows>
        <Row>
            <Value isNull="true"></Value>
            <Value>0</Value>
            <Value>0.1</Value>
        </Row>
        <Row>
            <Value>KQV</Value>
            <Value>1</Value>
            <Value>0.15</Value>
        </Row>
        <Row>
            <Value isNull="false">NV</Value>
            <Value isNull="false">0</Value>
            <Value isNull="false">0.2</Value>
        </Row>
        <Row>
            <Value isNull="false">NV</Value>
            <Value isNull="false">1</Value>
            <Value isNull="false">0.25</Value>
        </Row>
        <Row>
            <Value isNull="false">BBV</Value>
            <Value isNull="false">0</Value>
            <Value isNull="false">0.3</Value>
        </Row>
        <Row>
            <Value isNull="false">BBV</Value>
            <Value isNull="false">1</Value>
            <Value isNull="false">0.35</Value>
        </Row>
    </Rows>
</TableContents>
